#### Preprocessing Data

In [58]:
import re
import pandas as pd

In [59]:
f = open('chat/satya.txt','r',encoding='utf-8')

In [60]:
data = f.read()

In [61]:
print(type(data))

<class 'str'>

In [62]:
print(data)

10/05/2025, 12:52 am - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*
10/05/2025, 12:52 am - Satya Prasad Avn Cse: <Media omitted>
10/05/2025, 12:55 am - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 10:20 am - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 10:20 am - Satya Prasad Avn Cse: Pick one
17/05/2025, 10:20 am - Satya Prasad Avn Cse: Fast 💨
17/05/2025, 10:21 am - Satya Prasad Avn Cse: All are red roses
17/05/2025, 10:22 am - vijay: Inka em types leva mawa
17/05/2025, 10:22 am - Satya Prasad Avn Cse: Niku em kavali cheppu
17/05/2025, 10:22 am - vijay: Wait
17/05/2025, 10:22 am - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 10:22 am - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 10:23 am - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 10:23 am - vijay: <Media omitted>
17/05/2025, 10:23 am - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 10:23 am - vijay: Ee type lo avutadha
17/05/2025, 10:23 am - Satya Prasad Avn Cse: Special type
17/05/2025, 10:24 am - Satya Prasad Avn Cse: Ledhu anta ra
17/05/2025, 10:24 am - vijay: Different rose colors leva
17/05/2025, 10:25 am - Satya Prasad Avn Cse: Red vundu
17/05/2025, 10:25 am - Satya Prasad Avn Cse: Vundi
17/05/2025, 10:25 am - vijay: Wait
17/05/2025, 10:29 am - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 10:29 am - vijay: Oka sare ne pakkane una pic pampu
17/05/2025, 10:29 am - Satya Prasad Avn Cse:
17/05/2025, 10:29 am - vijay: <Media omitted>
17/05/2025, 10:31 am - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 10:31 am - Satya Prasad Avn Cse: Bunch of 10 istadu anta 280
17/05/2025, 10:33 am - Satya Prasad Avn Cse:
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
17/05/2025, 5:33 pm - Satya Prasad Avn Cse: <Media omitted>
18/05/2025, 10:11 am - vijay: Aree satya
18/05/2025, 10:12 am - vijay: Thana single pics pampu ra
18/05/2025, 10:12 am - Satya Prasad Avn Cse: Haa
18/05/2025, 10:12 am - Satya Prasad Avn Cse: Levu ra
18/05/2025, 10:12 am - vijay: Ne phone lo thesav ga ra
18/05/2025, 10:12 am - Satya Prasad Avn Cse: <Media omitted>
18/05/2025, 10:12 am - Satya Prasad Avn Cse: <Media omitted>
18/05/2025, 10:12 am - Satya Prasad Avn Cse: Only 2 pics eh vunayi
18/05/2025, 10:12 am - vijay: Sare
18/05/2025, 10:12 am - vijay: Eeroju match unada
18/05/2025, 10:13 am - vijay: Cricket
18/05/2025, 10:13 am - Satya Prasad Avn Cse: Emo ra
18/05/2025, 10:13 am - Satya Prasad Avn Cse: Ni istam
18/05/2025, 10:14 am - vijay: Orey cricket match anaru ga ra
18/05/2025, 10:14 am - vijay: Em ayindhe ane adugutuna
18/05/2025, 10:15 am - Satya Prasad Avn Cse: Emo ra evad em chepale naku kuda
18/05/2025, 10:15 am - vijay: Okay le ra
22/05/2025, 11:55 am - Satya Prasad Avn Cse: https://maps.app.goo.gl/gKBWf5fHZ21zGkzo8?g_st=aw
22/05/2025, 11:58 am - vijay: Hostel ki vachai mawa
22/05/2025, 11:58 am - vijay: Iddaram kalise veldam
22/05/2025, 11:58 am - Satya Prasad Avn Cse: Rey
22/05/2025, 11:59 am - vijay: Bike ledu mawa
22/05/2025, 12:00 pm - Satya Prasad Avn Cse: Dev nannu jetin ni pick chesukomandu
22/05/2025, 12:00 pm - vijay: Oka sare wait chey mawa
31/05/2025, 11:24 am - Satya Prasad Avn Cse: <Media omitted>
31/05/2025, 11:43 am - vijay: <Media omitted>
04/06/2025, 1:10 pm - vijay: location: https://maps.google.com/?q=16.4008431,78.6351825
05/06/2025, 1:46 pm - Satya Prasad Avn Cse: 1145
05/06/2025, 4:13 pm - vijay: 152 km
06/06/2025, 2:36 pm - vijay: Rey
06/06/2025, 2:37 pm - vijay: Torcher ga undi ra
06/06/2025, 2:37 pm - vijay: Vellu golla
06/06/2025, 2:37 pm - Satya Prasad Avn Cse: 😂
06/06/2025, 2:37 pm - Satya Prasad Avn Cse: Enduku em ayindi
06/06/2025, 2:37 pm - vijay: Biyatike tesikoni veltunadu
06/06/2025, 2:37 pm - vijay: Thinadanike ane burra thintunadu
06/06/2025, 2:38 pm - Satya Prasad Avn Cse: 😂
06/06/2025, 2:38 pm - vijay: Na degira amount levu ra ane ana
06/06/2025, 2:38 pm - Satya Prasad Avn Cse: Nenu vastale
06/06/2025, 2:38 pm - vijay: Torcher ga undi ra
06/06/2025, 2:38 pm - vijay: Ippude cheptundu
06/06/2025, 2:39 pm - vijay: Prepare avutuna ra ane ana gane tesikoni veltunaru
06/06/2025, 2:39 pm - vijay: Valla tho ayithe veltav ma tho ayithe ravu ane antunaru ra
06/06/2025, 2:39 pm - Satya Prasad Avn Cse: Cheppu interest ledu ani
06/06/2025, 2:39 pm - vijay: Entha Chepina ardam chasekovataledu
06/06/2025, 2:39 pm - vijay: Hstl ki vachadu dev gadu
06/06/2025, 2:40 pm - Satya Prasad Avn Cse: Vellu mari tinesi ra
06/06/2025, 2:41 pm - vijay: Karma mawa
06/06/2025, 2:41 pm - Satya Prasad Avn Cse: Enjoy chey ra
06/06/2025, 2:43 pm - vijay: Pandu ki chepte full kopam ga undi
06/06/2025, 2:43 pm - Satya Prasad Avn Cse: 😂😂😂
06/06/2025, 2:44 pm - Satya Prasad Avn Cse: Manchiga ayindi
06/06/2025, 2:44 pm - vijay: Karma ra
06/06/2025, 6:55 pm - Satya Prasad Avn Cse: <Media omitted>
06/06/2025, 7:00 pm - vijay: Wait
06/06/2025, 7:00 pm - vijay: Vintuna ra
06/06/2025, 7:00 pm - Satya Prasad Avn Cse: Ok 👍
06/06/2025, 7:15 pm - vijay: Lite tesiko mawa
06/06/2025, 7:20 pm - vijay: Karthik tho matladutuna
11/06/2025, 10:16 pm - Satya Prasad Avn Cse: <Media omitted>
11/06/2025, 10:18 pm - Satya Prasad Avn Cse: This message was deleted
11/06/2025, 11:54 pm - Satya Prasad Avn Cse: 1330 iyali
12/06/2025, 10:22 am - vijay: 80 water bottle delete chesara
14/06/2025, 12:52 pm - vijay:
17/06/2025, 10:39 pm - vijay: Cl lift mawa
18/06/2025, 10:12 am - Satya Prasad Avn Cse: Use this link to friend me on Chess.com and let's play sometime!

https://link.chess.com/friend/C6mmxO
20/06/2025, 8:43 pm - Satya Prasad Avn Cse: https://maps.app.goo.gl/bN5j38FqtVQzZRFQ9?g_st=iw
21/06/2025, 7:34 am - vijay: <Media omitted>
21/06/2025, 7:34 am - vijay: <Media omitted>
21/06/2025, 7:34 am - vijay: Explain plzz
27/06/2025, 10:49 am - vijay:
27/06/2025, 10:49 am - vijay: <Media omitted>
27/06/2025, 10:49 am - vijay: <Media omitted>
27/06/2025, 10:49 am - vijay: <Media omitted>
27/06/2025, 10:49 am - vijay: <Media omitted>
27/06/2025, 10:49 am - vijay: <Media omitted>
27/06/2025, 10:49 am - vijay: <Media omitted>
27/06/2025, 10:49 am - vijay: <Media omitted>
27/06/2025, 5:51 pm - Satya Prasad Avn Cse: Syllabus copy send
27/06/2025, 5:51 pm - Satya Prasad Avn Cse:
27/06/2025, 6:02 pm - vijay: <Media omitted>
27/06/2025, 6:57 pm - Satya Prasad Avn Cse: Night explain chey ra
30/06/2025, 11:29 pm - vijay: 😳
30/06/2025, 11:29 pm - vijay: Mawa repu tshirt tesikoni rara
30/06/2025, 11:29 pm - vijay: Pandu adugutundhe
07/07/2025, 4:28 pm - vijay:
07/07/2025, 6:47 pm - Satya Prasad Avn Cse:
07/07/2025, 6:53 pm - vijay:
07/07/2025, 7:29 pm - Satya Prasad Avn Cse:
09/07/2025, 9:33 am - vijay:
09/07/2025, 4:40 pm - vijay:
12/07/2025, 1:18 pm - Satya Prasad Avn Cse: Arey
12/07/2025, 1:18 pm - Satya Prasad Avn Cse: Money set ayithe transfer chey iroju pay cheyali
12/07/2025, 2:41 pm - vijay: Sare mawa
12/07/2025, 2:41 pm - vijay: Chesta eeroju
13/07/2025, 3:41 am - vijay: Don't worry I have a plan
13/07/2025, 3:42 am - Satya Prasad Avn Cse: 😂😂
13/07/2025, 3:42 am - vijay: I will handle
13/07/2025, 3:42 am - vijay: Repu asritha degiraki veltadhe chudu
13/07/2025, 3:42 am - vijay: Through laddu
13/07/2025, 8:28 am - vijay: Mava
13/07/2025, 9:18 am - Satya Prasad Avn Cse: Ha
13/07/2025, 9:18 am - Satya Prasad Avn Cse: Cheppu
13/07/2025, 5:54 pm - Satya Prasad Avn Cse:
15/07/2025, 12:09 pm - vijay: Shower ki veltuna
15/07/2025, 12:10 pm - vijay: Vachaka cl chesta
15/07/2025, 12:10 pm - vijay: Meru start avandi
18/07/2025, 12:24 pm - vijay: https://youtube.com/playlist?list=PLA1HLruLdexQSI5Vxh-UgnW1eNa5ksZmr&si=ekOwhV9pBsxn3MGL
02/08/2025, 2:59 pm - Satya Prasad Avn Cse:
02/08/2025, 3:00 pm - vijay:
02/08/2025, 3:00 pm - Satya Prasad Avn Cse: Message chey
02/08/2025, 3:00 pm - Satya Prasad Avn Cse: Or voice message send chey
08/08/2025, 5:44 pm - Satya Prasad Avn Cse: <Media omitted>
09/08/2025, 10:34 am - vijay: Rey
10/08/2025, 10:38 am - vijay:
10/08/2025, 10:56 am - vijay:
10/08/2025, 11:00 am - Satya Prasad Avn Cse:
10/08/2025, 11:00 am - vijay:
10/08/2025, 11:00 am - vijay:
11/08/2025, 5:03 pm - vijay: Hlooooo
11/08/2025, 5:03 pm - Satya Prasad Avn Cse: location: https://maps.google.com/?q=17.343311309814453,78.55595397949219
11/08/2025, 5:03 pm - Satya Prasad Avn Cse: Entha time .?
11/08/2025, 5:08 pm - vijay: https://maps.app.goo.gl/EhpVTkHbMmJnYGEa6?g_st=awb
11/08/2025, 5:09 pm - Satya Prasad Avn Cse: location: https://maps.google.com/?q=17.336925506591797,78.57341766357422
11/08/2025, 6:01 pm - Satya Prasad Avn Cse:
11/08/2025, 6:01 pm - Satya Prasad Avn Cse: <Media omitted>
11/08/2025, 6:01 pm - Satya Prasad Avn Cse: <Media omitted>
11/08/2025, 6:01 pm - Satya Prasad Avn Cse: <Media omitted>
11/08/2025, 6:01 pm - Satya Prasad Avn Cse: <Media omitted>
22/08/2025, 6:10 pm - Satya Prasad Avn Cse:
24/08/2025, 10:53 pm - Satya Prasad Avn Cse: Call button mida hand shake ayitondi 😂😂
25/08/2025, 10:58 am - vijay: Rey Inka apa ra
30/08/2025, 4:57 pm - vijay: <Media omitted>
30/08/2025, 5:15 pm - Satya Prasad Avn Cse: Thanks ra
03/09/2025, 11:39 pm - Satya Prasad Avn Cse: <Media omitted>
03/09/2025, 11:39 pm - Satya Prasad Avn Cse: Open ayitale ra
03/09/2025, 11:45 pm - vijay: Same situation ra
03/09/2025, 11:45 pm - Satya Prasad Avn Cse: 🥲🥲
03/09/2025, 11:45 pm - vijay: Try
03/09/2025, 11:45 pm - Satya Prasad Avn Cse: Chestunna
03/09/2025, 11:46 pm - Satya Prasad Avn Cse: Niku open ayithe cheppu
03/09/2025, 11:47 pm - vijay: Sare ra
04/09/2025, 11:16 pm - vijay: <Media omitted>
09/09/2025, 6:22 pm - vijay: <Media omitted>
11/09/2025, 4:54 pm - Satya Prasad Avn Cse: Source: Forbes https://share.google/LjJkItsUjrC9SYGm3
11/09/2025, 4:54 pm - Satya Prasad Avn Cse: Source: YouTube https://share.google/6VHQKP0egv0D9MFyx
11/09/2025, 4:55 pm - Satya Prasad Avn Cse: Source: Nasdaq https://share.google/IDsn5YnkAQuK3ohiE
11/09/2025, 4:55 pm - Satya Prasad Avn Cse: Source: The White House (.gov) https://share.google/XPrvjmoZomZFTakw2
11/09/2025, 4:57 pm - Satya Prasad Avn Cse: Nasdaq
11/09/2025, 4:57 pm - Satya Prasad Avn Cse: Original us govt
13/09/2025, 8:46 pm - Satya Prasad Avn Cse: This message was deleted
24/09/2025, 11:21 am - vijay: <Media omitted>
24/09/2025, 11:22 am - vijay: <Media omitted>
24/09/2025, 11:23 am - vijay: <Media omitted>
24/09/2025, 11:23 am - Satya Prasad Avn Cse: Nice ra
24/09/2025, 11:23 am - Satya Prasad Avn Cse: Tisuko
24/09/2025, 11:23 am - Satya Prasad Avn Cse: Plain
24/09/2025, 11:23 am - vijay: This
24/09/2025, 11:23 am - Satya Prasad Avn Cse: No
24/09/2025, 11:23 am - vijay: Sare plane fix
24/09/2025, 11:24 am - vijay: Vachinapudu tesikundam
24/09/2025, 11:24 am - Satya Prasad Avn Cse: Ok 👍
24/09/2025, 11:24 am - vijay: Ippudu vadu already hstl ki vachadu anta
24/09/2025, 11:24 am - Satya Prasad Avn Cse: Ok 👍
24/09/2025, 8:18 pm - vijay: Hello
24/09/2025, 8:19 pm - Satya Prasad Avn Cse:
24/09/2025, 8:19 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:19 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:19 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:19 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:19 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:19 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:19 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:20 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:22 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:22 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:22 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:22 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:22 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:27 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:27 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:28 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:28 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:30 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:30 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:31 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:32 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:33 pm - Satya Prasad Avn Cse: <Media omitted>
24/09/2025, 8:33 pm - Satya Prasad Avn Cse: <Media omitted>
25/09/2025, 7:34 pm - vijay: Raledu mawa
25/09/2025, 7:35 pm - Satya Prasad Avn Cse: Ok 👍
27/09/2025, 1:32 am - Satya Prasad Avn Cse: Arey
27/09/2025, 1:32 am - Satya Prasad Avn Cse: Mama
27/09/2025, 1:32 am - Satya Prasad Avn Cse: Ippude intiki vacha
27/09/2025, 8:35 pm - vijay: <Media omitted>
27/09/2025, 8:36 pm - Satya Prasad Avn Cse: Check chey okasari
27/09/2025, 8:36 pm - Satya Prasad Avn Cse: 215U1A6243
27/09/2025, 8:36 pm - vijay: 6243
27/09/2025, 8:36 pm - vijay: Ledu bey
27/09/2025, 8:36 pm - Satya Prasad Avn Cse: Ledhu na number
27/09/2025, 8:36 pm - vijay: Ha
27/09/2025, 8:36 pm - Satya Prasad Avn Cse: Haa ade kada
08/10/2025, 2:37 pm - Satya Prasad Avn Cse: Hlo
08/10/2025, 3:22 pm - vijay: Chepu mawa
08/10/2025, 4:17 pm - Satya Prasad Avn Cse: ✌️
10/10/2025, 5:15 pm - vijay: <Media omitted>
10/10/2025, 7:29 pm - vijay: Follow the Ds Hometuitions channel on WhatsApp: https://whatsapp.com/channel/0029Vb7Frs82975GSKoiPg2d
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:44 pm - Satya Prasad Avn Cse: <Media omitted>
23/10/2025, 8:46 pm - vijay: <Media omitted>
23/10/2025, 8:46 pm - vijay: 1
23/10/2025, 8:46 pm - vijay: <Media omitted>
23/10/2025, 8:47 pm - vijay: <Media omitted>
23/10/2025, 8:47 pm - vijay: 2
23/10/2025, 8:47 pm - vijay: <Media omitted>
23/10/2025, 8:47 pm - Satya Prasad Avn Cse: Ok 🆗
23/10/2025, 8:47 pm - vijay: 3rd
28/10/2025, 12:58 pm - vijay: <Media omitted>
03/11/2025, 9:03 am - vijay: Bhai
03/11/2025, 9:03 am - vijay: College ki vellale
03/11/2025, 9:11 am - vijay:
03/11/2025, 11:41 am - vijay: <Media omitted>
03/11/2025, 11:41 am - Satya Prasad Avn Cse: Thanks ra ✌️
03/11/2025, 11:47 am - vijay: 🖕U
03/11/2025, 11:47 am - Satya Prasad Avn Cse: 😂
06/11/2025, 7:57 am - vijay: Cake cut chedam mawa
06/11/2025, 7:57 am - vijay: 8 ki
06/11/2025, 7:57 am - vijay: Evening
06/11/2025, 7:57 am - vijay: Bakers Den
06/11/2025, 1:01 pm - vijay:
22/11/2025, 5:50 pm - Satya Prasad Avn Cse: Rey
22/11/2025, 5:50 pm - Satya Prasad Avn Cse: Call chesav
22/11/2025, 5:50 pm - Satya Prasad Avn Cse: Mali cheste call lepav em ra
22/11/2025, 5:50 pm - Satya Prasad Avn Cse: Balisinda
22/11/2025, 5:58 pm - vijay: 🤣🤣🤣
30/11/2025, 10:03 am - Satya Prasad Avn Cse:
30/11/2025, 10:03 am - vijay:
08/12/2025, 9:48 am - Satya Prasad Avn Cse: Cns notes send cheyava
08/12/2025, 9:53 am - vijay: Levu mawa
08/12/2025, 10:04 am - Satya Prasad Avn Cse: Set chey ra
08/12/2025, 10:04 am - vijay: Try chase chepta mawa
25/12/2025, 4:55 pm - Satya Prasad Avn Cse: <Media omitted>
25/12/2025, 4:56 pm - Satya Prasad Avn Cse: <Media omitted>
01/01/2026, 2:06 pm - Satya Prasad Avn Cse: https://share.google/KuuyXRCIZNoR5uGhJ
01/01/2026, 2:06 pm - Satya Prasad Avn Cse: https://share.google/omLh7Y7OFZuvv3GzW
01/01/2026, 2:06 pm - Satya Prasad Avn Cse: https://share.google/KNerVphwmDu3ovdKA
01/01/2026, 2:06 pm - Satya Prasad Avn Cse: https://share.google/GFwRB0O8Wjdbg5lU4
06/01/2026, 12:17 pm - vijay:
17/01/2026, 5:41 pm - Satya Prasad Avn Cse:
17/01/2026, 5:42 pm - Satya Prasad Avn Cse: Arey
17/01/2026, 5:42 pm - Satya Prasad Avn Cse: Money vunte oka 1000 kottu
17/01/2026, 7:08 pm - vijay: Levu ra mawa
17/01/2026, 7:08 pm - vijay: Nen biyata una
17/01/2026, 7:23 pm - Satya Prasad Avn Cse: 👍
18/01/2026, 1:27 pm - Satya Prasad Avn Cse: Results vachaya
18/01/2026, 5:18 pm - vijay: Emo ra
18/01/2026, 5:18 pm - vijay: Inka chudaledu
18/01/2026, 5:44 pm - Satya Prasad Avn Cse: Okasari chudava
18/01/2026, 9:00 pm - vijay: ee week lo vastai anta ra
18/01/2026, 9:00 pm - vijay: 4th year vi ayithe feb lo vastai
18/01/2026, 9:58 pm - Satya Prasad Avn Cse: Ok ra
19/01/2026, 7:36 pm - vijay: voice  vinipinchataledu
19/01/2026, 7:46 pm - Satya Prasad Avn Cse: Haa
19/01/2026, 7:46 pm - Satya Prasad Avn Cse: Saturday going to jetin home
19/01/2026, 8:08 pm - vijay: lets see
03/02/2026, 4:41 pm - Satya Prasad Avn Cse:
03/02/2026, 4:44 pm - vijay: <Media omitted>
04/02/2026, 11:06 am - Satya Prasad Avn Cse: Sensex 73600 put 240 to 263
04/02/2026, 11:06 am - Satya Prasad Avn Cse: Target hit
04/02/2026, 11:10 am - Satya Prasad Avn Cse: Trade on resistance, support and oi
04/02/2026, 11:15 am - Satya Prasad Avn Cse: 300
04/02/2026, 11:34 am - vijay: chustunava
04/02/2026, 11:35 am - vijay: nen chudata ledu ra market ni
04/02/2026, 11:35 am - vijay: classes unai
04/02/2026, 11:35 am - vijay: busy ayepoyina
04/02/2026, 11:39 am - Satya Prasad Avn Cse: Ok 👍
05/02/2026, 9:33 am - Satya Prasad Avn Cse: Sensex 83500 put 160 enter stoploss 150 target 180
05/02/2026, 9:33 am - Satya Prasad Avn Cse: 177 sell
05/02/2026, 9:49 am - Satya Prasad Avn Cse: <Media omitted>
05/02/2026, 9:49 am - Satya Prasad Avn Cse: <Media omitted>
05/02/2026, 9:58 am - vijay: inka trade tesikoku
05/02/2026, 9:58 am - Satya Prasad Avn Cse: Ha tisukole
05/02/2026, 9:59 am - vijay: free time lo whatsapp cl chey
05/02/2026, 10:00 am - vijay: koncham matladali
05/02/2026, 10:00 am - Satya Prasad Avn Cse: Ha ra
05/02/2026, 10:00 am - Satya Prasad Avn Cse: Cheppu
05/02/2026, 10:01 am - Satya Prasad Avn Cse:
05/02/2026, 10:12 am - Satya Prasad Avn Cse: <Media omitted>
05/02/2026, 10:12 am - Satya Prasad Avn Cse: <Media omitted>
05/02/2026, 10:36 am - Satya Prasad Avn Cse:
05/02/2026, 11:04 am - Satya Prasad Avn Cse:
05/02/2026, 11:08 am - Satya Prasad Avn Cse:
05/02/2026, 11:11 am - vijay: https://meet.google.com/zrv-hmfx-xap

In [63]:
pattern = r'\d{1,2}/\d{1,2}/\d{4},\s\d{1,2}:\d{2}\s*[ap]m\s-\s'

In [64]:
messages = re.split(pattern, data)[1:]
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: Pick one\n',
 'Satya Prasad Avn Cse: Fast 💨\n',
 'Satya Prasad Avn Cse: All are red roses\n',
 'vijay: Inka em types leva mawa\n',
 'Satya Prasad Avn Cse: Niku em kavali cheppu\n',
 'vijay: Wait\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: Ee type lo avutadha\n',
 'Satya Prasad Avn Cse: Special type\n',
 'Satya Prasad Avn Cse: Ledhu anta ra\n',
 'vijay: Different rose colors leva\n',
 'Satya Prasad Avn Cse: Red vundu\n',
 'Satya Prasad Avn Cse: Vundi\n',
 'vijay: Wait\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: Oka sare ne pakkane una pic pampu\n',
 'Satya Prasad Avn Cse: \n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: Bunch of 10 istadu anta 280\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: Aree satya\n',
 'vijay: Thana single pics pampu ra\n',
 'Satya Prasad Avn Cse: Haa\n',
 'Satya Prasad Avn Cse: Levu ra\n',
 'vijay: Ne phone lo thesav ga ra\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: Only 2 pics eh vunayi\n',
 'vijay: Sare\n',
 'vijay: Eeroju match unada\n',
 'vijay: Cricket\n',
 'Satya Prasad Avn Cse: Emo ra\n',
 'Satya Prasad Avn Cse: Ni istam\n',
 'vijay: Orey cricket match anaru ga ra\n',
 'vijay: Em ayindhe ane adugutuna\n',
 'Satya Prasad Avn Cse: Emo ra evad em chepale naku kuda\n',
 'vijay: Okay le ra\n',
 'Satya Prasad Avn Cse: https://maps.app.goo.gl/gKBWf5fHZ21zGkzo8?g_st=aw\n',
 'vijay: Hostel ki vachai mawa\n',
 'vijay: Iddaram kalise veldam\n',
 'Satya Prasad Avn Cse: Rey\n',
 'vijay: Bike ledu mawa\n',
 'Satya Prasad Avn Cse: Dev nannu jetin ni pick chesukomandu\n',
 'vijay: Oka sare wait chey mawa\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: location: https://maps.google.com/?q=16.4008431,78.6351825\n',
 'Satya Prasad Avn Cse: 1145\n',
 'vijay: 152 km\n',
 'vijay: Rey\n',
 'vijay: Torcher ga undi ra\n',
 'vijay: Vellu golla\n',
 'Satya Prasad Avn Cse: 😂\n',
 'Satya Prasad Avn Cse: Enduku em ayindi\n',
 'vijay: Biyatike tesikoni veltunadu\n',
 'vijay: Thinadanike ane burra thintunadu\n',
 'Satya Prasad Avn Cse: 😂\n',
 'vijay: Na degira amount levu ra ane ana\n',
 'Satya Prasad Avn Cse: Nenu vastale\n',
 'vijay: Torcher ga undi ra\n',
 'vijay: Ippude cheptundu\n',
 'vijay: Prepare avutuna ra ane ana gane tesikoni veltunaru\n',
 'vijay: Valla tho ayithe veltav ma tho ayithe ravu ane antunaru ra\n',
 'Satya Prasad Avn Cse: Cheppu interest ledu ani\n',
 'vijay: Entha Chepina ardam chasekovataledu\n',
 'vijay: Hstl ki vachadu dev gadu\n',
 'Satya Prasad Avn Cse: Vellu mari tinesi ra\n',
 'vijay: Karma mawa\n',
 'Satya Prasad Avn Cse: Enjoy chey ra\n',
 'vijay: Pandu ki chepte full kopam ga undi\n',
 'Satya Prasad Avn Cse: 😂😂😂\n',
 'Satya Prasad Avn Cse: Manchiga ayindi\n',
 'vijay: Karma ra\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: Wait\n',
 'vijay: Vintuna ra\n',
 'Satya Prasad Avn Cse: Ok 👍\n',
 'vijay: Lite tesiko mawa\n',
 'vijay: Karthik tho matladutuna\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: This message was deleted\n',
 'Satya Prasad Avn Cse: 1330 iyali\n',
 'vijay: 80 water bottle delete chesara\n',
 'vijay: \n',
 'vijay: Cl lift mawa\n',
 "Satya Prasad Avn Cse: Use this link to friend me on Chess.com and let's play sometime! \n\nhttps://link.chess.com/friend/C6mmxO\n",
 'Satya Prasad Avn Cse: https://maps.app.goo.gl/bN5j38FqtVQzZRFQ9?g_st=iw\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: Explain plzz\n',
 'vijay: \n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: Syllabus copy send\n',
 'Satya Prasad Avn Cse: \n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: Night explain chey ra\n',
 'vijay: 😳\n',
 'vijay: Mawa repu tshirt tesikoni rara\n',
 'vijay: Pandu adugutundhe\n',
 'vijay: \n',
 'Satya Prasad Avn Cse: \n',
 'vijay: \n',
 'Satya Prasad Avn Cse: \n',
 'vijay: \n',
 'vijay: \n',
 'Satya Prasad Avn Cse: Arey\n',
 'Satya Prasad Avn Cse: Money set ayithe transfer chey iroju pay cheyali\n',
 'vijay: Sare mawa\n',
 'vijay: Chesta eeroju\n',
 "vijay: Don't worry I have a plan\n",
 'Satya Prasad Avn Cse: 😂😂\n',
 'vijay: I will handle\n',
 'vijay: Repu asritha degiraki veltadhe chudu\n',
 'vijay: Through laddu\n',
 'vijay: Mava\n',
 'Satya Prasad Avn Cse: Ha\n',
 'Satya Prasad Avn Cse: Cheppu\n',
 'Satya Prasad Avn Cse: \n',
 'vijay: Shower ki veltuna\n',
 'vijay: Vachaka cl chesta\n',
 'vijay: Meru start avandi\n',
 'vijay: https://youtube.com/playlist?list=PLA1HLruLdexQSI5Vxh-UgnW1eNa5ksZmr&si=ekOwhV9pBsxn3MGL\n',
 'Satya Prasad Avn Cse: \n',
 'vijay: \n',
 'Satya Prasad Avn Cse: Message chey\n',
 'Satya Prasad Avn Cse: Or voice message send chey\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: Rey\n',
 'vijay: \n',
 'vijay: \n',
 'Satya Prasad Avn Cse: \n',
 'vijay: \n',
 'vijay: \n',
 'vijay: Hlooooo\n',
 'Satya Prasad Avn Cse: location: https://maps.google.com/?q=17.343311309814453,78.55595397949219\n',
 'Satya Prasad Avn Cse: Entha time .?\n',
 'vijay: https://maps.app.goo.gl/EhpVTkHbMmJnYGEa6?g_st=awb\n',
 'Satya Prasad Avn Cse: location: https://maps.google.com/?q=17.336925506591797,78.57341766357422\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: Call button mida hand shake ayitondi 😂😂\n',
 'vijay: Rey Inka apa ra\n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: Thanks ra\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: Open ayitale ra\n',
 'vijay: Same situation ra\n',
 'Satya Prasad Avn Cse: 🥲🥲\n',
 'vijay: Try\n',
 'Satya Prasad Avn Cse: Chestunna\n',
 'Satya Prasad Avn Cse: Niku open ayithe cheppu\n',
 'vijay: Sare ra\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: Source: Forbes https://share.google/LjJkItsUjrC9SYGm3\n',
 'Satya Prasad Avn Cse: Source: YouTube https://share.google/6VHQKP0egv0D9MFyx\n',
 'Satya Prasad Avn Cse: Source: Nasdaq https://share.google/IDsn5YnkAQuK3ohiE\n',
 'Satya Prasad Avn Cse: Source: The White House (.gov) https://share.google/XPrvjmoZomZFTakw2\n',
 'Satya Prasad Avn Cse: Nasdaq\n',
 'Satya Prasad Avn Cse: Original us govt\n',
 'Satya Prasad Avn Cse: This message was deleted\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: Nice ra\n',
 'Satya Prasad Avn Cse: Tisuko\n',
 'Satya Prasad Avn Cse: Plain\n',
 'vijay: This\n',
 'Satya Prasad Avn Cse: No\n',
 'vijay: Sare plane fix\n',
 'vijay: Vachinapudu tesikundam\n',
 'Satya Prasad Avn Cse: Ok 👍\n',
 'vijay: Ippudu vadu already hstl ki vachadu anta\n',
 'Satya Prasad Avn Cse: Ok 👍\n',
 'vijay: Hello\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: Raledu mawa\n',
 'Satya Prasad Avn Cse: Ok 👍\n',
 'Satya Prasad Avn Cse: Arey\n',
 'Satya Prasad Avn Cse: Mama\n',
 'Satya Prasad Avn Cse: Ippude intiki vacha\n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: Check chey okasari\n',
 'Satya Prasad Avn Cse: 215U1A6243\n',
 'vijay: 6243\n',
 'vijay: Ledu bey\n',
 'Satya Prasad Avn Cse: Ledhu na number\n',
 'vijay: Ha\n',
 'Satya Prasad Avn Cse: Haa ade kada\n',
 'Satya Prasad Avn Cse: Hlo\n',
 'vijay: Chepu mawa\n',
 'Satya Prasad Avn Cse: ✌️\n',
 'vijay: <Media omitted>\n',
 'vijay: Follow the Ds Hometuitions channel on WhatsApp: https://whatsapp.com/channel/0029Vb7Frs82975GSKoiPg2d\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: 1\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'vijay: 2\n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: Ok 🆗\n',
 'vijay: 3rd\n',
 'vijay: <Media omitted>\n',
 'vijay: Bhai\n',
 'vijay: College ki vellale\n',
 'vijay: \n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: Thanks ra ✌️\n',
 'vijay: 🖕U\n',
 'Satya Prasad Avn Cse: 😂\n',
 'vijay: Cake cut chedam mawa\n',
 'vijay: 8 ki\n',
 'vijay: Evening\n',
 'vijay: Bakers Den\n',
 'vijay: \n',
 'Satya Prasad Avn Cse: Rey\n',
 'Satya Prasad Avn Cse: Call chesav\n',
 'Satya Prasad Avn Cse: Mali cheste call lepav em ra\n',
 'Satya Prasad Avn Cse: Balisinda\n',
 'vijay: 🤣🤣🤣\n',
 'Satya Prasad Avn Cse: \n',
 'vijay: \n',
 'Satya Prasad Avn Cse: Cns notes send cheyava\n',
 'vijay: Levu mawa\n',
 'Satya Prasad Avn Cse: Set chey ra\n',
 'vijay: Try chase chepta mawa\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: https://share.google/KuuyXRCIZNoR5uGhJ\n',
 'Satya Prasad Avn Cse: https://share.google/omLh7Y7OFZuvv3GzW\n',
 'Satya Prasad Avn Cse: https://share.google/KNerVphwmDu3ovdKA\n',
 'Satya Prasad Avn Cse: https://share.google/GFwRB0O8Wjdbg5lU4\n',
 'vijay: \n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: Arey\n',
 'Satya Prasad Avn Cse: Money vunte oka 1000 kottu\n',
 'vijay: Levu ra mawa\n',
 'vijay: Nen biyata una\n',
 'Satya Prasad Avn Cse: 👍\n',
 'Satya Prasad Avn Cse: Results vachaya\n',
 'vijay: Emo ra\n',
 'vijay: Inka chudaledu\n',
 'Satya Prasad Avn Cse: Okasari chudava\n',
 'vijay: ee week lo vastai anta ra\n',
 'vijay: 4th year vi ayithe feb lo vastai\n',
 'Satya Prasad Avn Cse: Ok ra\n',
 'vijay: voice  vinipinchataledu\n',
 'Satya Prasad Avn Cse: Haa\n',
 'Satya Prasad Avn Cse: Saturday going to jetin home\n',
 'vijay: lets see\n',
 'Satya Prasad Avn Cse: \n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: Sensex 73600 put 240 to 263\n',
 'Satya Prasad Avn Cse: Target hit\n',
 'Satya Prasad Avn Cse: Trade on resistance, support and oi\n',
 'Satya Prasad Avn Cse: 300\n',
 'vijay: chustunava\n',
 'vijay: nen chudata ledu ra market ni\n',
 'vijay: classes unai\n',
 'vijay: busy ayepoyina\n',
 'Satya Prasad Avn Cse: Ok 👍\n',
 'Satya Prasad Avn Cse: Sensex 83500 put 160 enter stoploss 150 target 180\n',
 'Satya Prasad Avn Cse: 177 sell\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: inka trade tesikoku\n',
 'Satya Prasad Avn Cse: Ha tisukole\n',
 'vijay: free time lo whatsapp cl chey\n',
 'vijay: koncham matladali\n',
 'Satya Prasad Avn Cse: Ha ra\n',
 'Satya Prasad Avn Cse: Cheppu\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: \n',
 'vijay: https://meet.google.com/zrv-hmfx-xap\n',
 'vijay: attend avu mawa\n',
 'vijay: https://meet.google.com/noa-dhnp-jyz\n',
 'vijay: come fast bro\n',
 'vijay: market is on trend\n',
 'Satya Prasad Avn Cse: 2 mins ra\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: Call?\n',
 'Satya Prasad Avn Cse: Meet end chesava ?\n',
 'vijay: ha chesa\n',
 'Satya Prasad Avn Cse: Ok\n',
 'vijay: good night\n',
 'vijay: poduko\n',
 'vijay: repu kaludam\n',
 'Satya Prasad Avn Cse: Haa\n',
 'vijay: 😂😂😂😂😂😂😂😂😂\n',
 'vijay: 9am ki meeting\n',
 'vijay: tomorrow\n',
 'Satya Prasad Avn Cse: Ok 👍\n',
 'vijay: repu friday\n',
 'vijay: trades chala kastam\n',
 'vijay: lets see\n',
 'Satya Prasad Avn Cse: Ha ra\n',
 'Satya Prasad Avn Cse: \n',
 'vijay: cl chesav bro\n',
 'Satya Prasad Avn Cse: Theta decay chustav ani chesina\n',
 'vijay: podukuna bro\n',
 'vijay: naku full experience undi\n',
 'Satya Prasad Avn Cse: Ok 👍\n',
 'vijay: repati niche 9 to 12\n',
 'vijay: market chudam\n',
 'vijay: time set avataledu\n',
 'Satya Prasad Avn Cse: Ha sare\n',
 'vijay: good night\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: Good morning\n',
 'vijay: Good morning mawa\n',
 'Satya Prasad Avn Cse: Chudama ?\n',
 'vijay: https://meet.google.com/bxs-whvb-mez\n',
 'vijay: https://meet.google.com/kvv-jbvn-nez\n',
 'vijay: https://meet.google.com/nct-kspz-och\n',
 'vijay: join avu\n',
 'vijay: <Media omitted>\n',
 'vijay: <Media omitted>\n',
 'Satya Prasad Avn Cse: location: https://maps.google.com/?q=17.362197875976562,78.52955627441406\n',
 'vijay: Started darling\n',
 'vijay: Omkar nagar\n',
 'Satya Prasad Avn Cse: Ok 👍\n',
 'vijay: Ne cap kavali\n',
 'vijay: Malle return lo ichesta\n',
 'Satya Prasad Avn Cse: Haaaa\n',
 'vijay: I am Eripilli Vijay, a B.Tech Final Year student in Data Science at AVN Institute of Engineering. I am submitting this Statement of Purpose to apply for an internship at the Indian Institute of Technology (IIT).\n\nMy academic background has equipped me with a strong foundation in Data Science, programming, and analytical problem-solving. I am keen on gaining hands-on exposure to research-oriented work and advanced technical practices. An internship at IIT will provide me with the opportunity to learn under expert guidance and enhance my practical and research skills.\n\nI am motivated, disciplined, and committed to making the most of this opportunity. I believe this internship will significantly contribute to my academic development and future career.\n\nI hereby declare that the information provided above is true and correct to the best of my knowledge.\n\nStudent Signature: ___________________________\nStudent Name: Eripilli Vijay\nRoll No / Register No: _______________________\nDepartment: Data Science\nCollege: AVN Institute of Engineering\nDate: ___________________\n\nRecommended & Verified By\n\nFaculty / HOD Name: _________________________\nDesignation: _______________________________\nDepartment: _______________________________\n\nSignature: _________________________________\n\nOfficial College Seal / Stamp:\n(Affix here)\n',
 'vijay: chudu bhai\n',
 'vijay: ide okay na\n',
 'Satya Prasad Avn Cse: Okay\n',
 'Satya Prasad Avn Cse: Okay\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: free ah\n',
 'Satya Prasad Avn Cse: \n',
 'vijay: Washroom lo una\n',
 'vijay: Wait\n',
 'vijay: Chesta\n',
 'vijay: Google meet link pamputha\n',
 "vijay: Don't worry\n",
 'Satya Prasad Avn Cse: ok\n',
 'vijay: https://meet.google.com/qxm-duog-rvv\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'Satya Prasad Avn Cse: <Media omitted>\n',
 'vijay: https://www.w3schools.com/html/html_basic.asp\n',
 'vijay: css kuda untadhe chudu\n',
 'Satya Prasad Avn Cse: Ha ra\n',
 'Satya Prasad Avn Cse: Thanks\n',
 'vijay: good mrng mawa\n',
 'vijay: eeroju trade tesikunte,afternoon tesikoku.\n',
 'vijay: <Media omitted>\n',
 'vijay: full sideways\n',
 'Satya Prasad Avn Cse: Ok\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: \n',
 'vijay: <Media omitted>\n',
 'vijay: To\nThe Internship Selection Committee\n[Institute Name]\n\nDear Sir/Madam,\n\nI strongly recommend Mr. Vijay [Last Name], a final-year B.Tech student at AVN Institution of Engineering, for your internship program. He is an academically strong, highly disciplined, and research-oriented student with excellent analytical and technical skills in Data Science and related domains.\n\nHis intellectual curiosity, work ethic, and ability to quickly grasp complex concepts distinguish him among his peers. I am confident he will contribute meaningfully and uphold the standards of your esteemed institution.\n\nI recommend him without reservation.\n\nSincerely,\n[Professor’s Name]\n[Designation], Department of [Dept Name]\nAVN Institution of Engineering\n\nSignature: ____________\nSeal\n',
 'vijay: see and give  me review\n',
 'Satya Prasad Avn Cse: Ok\n',
 'vijay: nv matter chudu ra\n',
 'vijay: plzz\n',
 'Satya Prasad Avn Cse: Mr erripalli Vijay\n',
 'vijay: niiiii\n',
 'vijay: change chesta ra\n',
 'Satya Prasad Avn Cse: 😂😂\n',
 'Satya Prasad Avn Cse: Antha ok\n',
 'vijay: tqssss\n',
 'Satya Prasad Avn Cse: 👍\n',
 'vijay: neku kuda ready cheyala\n',
 'Satya Prasad Avn Cse: Haa\n',
 'vijay: sare\n',
 'Satya Prasad Avn Cse: \n',
 'Satya Prasad Avn Cse: Haa\n',
 'Satya Prasad Avn Cse: Cheppu ra\n',
 'Satya Prasad Avn Cse: \n',
 'vijay: <Media omitted>\n',
 'vijay: anna ne cap teikoni ra\n',
 'vijay: 11 ki start avudam\n',
 'vijay: lechaka cl me\n',
 'Satya Prasad Avn Cse: https://studentservices.jntuh.ac.in/XIVconvocation/signUp.html\n',
 'Satya Prasad Avn Cse: Late ga podam\n',
 'vijay: You deleted this message\n',
 'vijay: Waiting for you mawa\n',
 'Satya Prasad Avn Cse: Eh babu\n',
 'Satya Prasad Avn Cse: Money set chey ra\n',
 'vijay: try chestuna mawa\n',
 'vijay: koncham time petting\n',

In [65]:
dates = re.findall(pattern, data)
dates

['10/05/2025, 12:52\u202fam - ',
 '10/05/2025, 12:52\u202fam - ',
 '10/05/2025, 12:55\u202fam - ',
 '17/05/2025, 10:20\u202fam - ',
 '17/05/2025, 10:20\u202fam - ',
 '17/05/2025, 10:20\u202fam - ',
 '17/05/2025, 10:21\u202fam - ',
 '17/05/2025, 10:22\u202fam - ',
 '17/05/2025, 10:22\u202fam - ',
 '17/05/2025, 10:22\u202fam - ',
 '17/05/2025, 10:22\u202fam - ',
 '17/05/2025, 10:22\u202fam - ',
 '17/05/2025, 10:23\u202fam - ',
 '17/05/2025, 10:23\u202fam - ',
 '17/05/2025, 10:23\u202fam - ',
 '17/05/2025, 10:23\u202fam - ',
 '17/05/2025, 10:23\u202fam - ',
 '17/05/2025, 10:24\u202fam - ',
 '17/05/2025, 10:24\u202fam - ',
 '17/05/2025, 10:25\u202fam - ',
 '17/05/2025, 10:25\u202fam - ',
 '17/05/2025, 10:25\u202fam - ',
 '17/05/2025, 10:29\u202fam - ',
 '17/05/2025, 10:29\u202fam - ',
 '17/05/2025, 10:29\u202fam - ',
 '17/05/2025, 10:29\u202fam - ',
 '17/05/2025, 10:31\u202fam - ',
 '17/05/2025, 10:31\u202fam - ',
 '17/05/2025, 10:33\u202fam - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '17/05/2025, 5:33\u202fpm - ',
 '18/05/2025, 10:11\u202fam - ',
 '18/05/2025, 10:12\u202fam - ',
 '18/05/2025, 10:12\u202fam - ',
 '18/05/2025, 10:12\u202fam - ',
 '18/05/2025, 10:12\u202fam - ',
 '18/05/2025, 10:12\u202fam - ',
 '18/05/2025, 10:12\u202fam - ',
 '18/05/2025, 10:12\u202fam - ',
 '18/05/2025, 10:12\u202fam - ',
 '18/05/2025, 10:12\u202fam - ',
 '18/05/2025, 10:13\u202fam - ',
 '18/05/2025, 10:13\u202fam - ',
 '18/05/2025, 10:13\u202fam - ',
 '18/05/2025, 10:14\u202fam - ',
 '18/05/2025, 10:14\u202fam - ',
 '18/05/2025, 10:15\u202fam - ',
 '18/05/2025, 10:15\u202fam - ',
 '22/05/2025, 11:55\u202fam - ',
 '22/05/2025, 11:58\u202fam - ',
 '22/05/2025, 11:58\u202fam - ',
 '22/05/2025, 11:58\u202fam - ',
 '22/05/2025, 11:59\u202fam - ',
 '22/05/2025, 12:00\u202fpm - ',
 '22/05/2025, 12:00\u202fpm - ',
 '31/05/2025, 11:24\u202fam - ',
 '31/05/2025, 11:43\u202fam - ',
 '04/06/2025, 1:10\u202fpm - ',
 '05/06/2025, 1:46\u202fpm - ',
 '05/06/2025, 4:13\u202fpm - ',
 '06/06/2025, 2:36\u202fpm - ',
 '06/06/2025, 2:37\u202fpm - ',
 '06/06/2025, 2:37\u202fpm - ',
 '06/06/2025, 2:37\u202fpm - ',
 '06/06/2025, 2:37\u202fpm - ',
 '06/06/2025, 2:37\u202fpm - ',
 '06/06/2025, 2:37\u202fpm - ',
 '06/06/2025, 2:38\u202fpm - ',
 '06/06/2025, 2:38\u202fpm - ',
 '06/06/2025, 2:38\u202fpm - ',
 '06/06/2025, 2:38\u202fpm - ',
 '06/06/2025, 2:38\u202fpm - ',
 '06/06/2025, 2:39\u202fpm - ',
 '06/06/2025, 2:39\u202fpm - ',
 '06/06/2025, 2:39\u202fpm - ',
 '06/06/2025, 2:39\u202fpm - ',
 '06/06/2025, 2:39\u202fpm - ',
 '06/06/2025, 2:40\u202fpm - ',
 '06/06/2025, 2:41\u202fpm - ',
 '06/06/2025, 2:41\u202fpm - ',
 '06/06/2025, 2:43\u202fpm - ',
 '06/06/2025, 2:43\u202fpm - ',
 '06/06/2025, 2:44\u202fpm - ',
 '06/06/2025, 2:44\u202fpm - ',
 '06/06/2025, 6:55\u202fpm - ',
 '06/06/2025, 7:00\u202fpm - ',
 '06/06/2025, 7:00\u202fpm - ',
 '06/06/2025, 7:00\u202fpm - ',
 '06/06/2025, 7:15\u202fpm - ',
 '06/06/2025, 7:20\u202fpm - ',
 '11/06/2025, 10:16\u202fpm - ',
 '11/06/2025, 10:18\u202fpm - ',
 '11/06/2025, 11:54\u202fpm - ',
 '12/06/2025, 10:22\u202fam - ',
 '14/06/2025, 12:52\u202fpm - ',
 '17/06/2025, 10:39\u202fpm - ',
 '18/06/2025, 10:12\u202fam - ',
 '20/06/2025, 8:43\u202fpm - ',
 '21/06/2025, 7:34\u202fam - ',
 '21/06/2025, 7:34\u202fam - ',
 '21/06/2025, 7:34\u202fam - ',
 '27/06/2025, 10:49\u202fam - ',
 '27/06/2025, 10:49\u202fam - ',
 '27/06/2025, 10:49\u202fam - ',
 '27/06/2025, 10:49\u202fam - ',
 '27/06/2025, 10:49\u202fam - ',
 '27/06/2025, 10:49\u202fam - ',
 '27/06/2025, 10:49\u202fam - ',
 '27/06/2025, 10:49\u202fam - ',
 '27/06/2025, 5:51\u202fpm - ',
 '27/06/2025, 5:51\u202fpm - ',
 '27/06/2025, 6:02\u202fpm - ',
 '27/06/2025, 6:57\u202fpm - ',
 '30/06/2025, 11:29\u202fpm - ',
 '30/06/2025, 11:29\u202fpm - ',
 '30/06/2025, 11:29\u202fpm - ',
 '07/07/2025, 4:28\u202fpm - ',
 '07/07/2025, 6:47\u202fpm - ',
 '07/07/2025, 6:53\u202fpm - ',
 '07/07/2025, 7:29\u202fpm - ',
 '09/07/2025, 9:33\u202fam - ',
 '09/07/2025, 4:40\u202fpm - ',
 '12/07/2025, 1:18\u202fpm - ',
 '12/07/2025, 1:18\u202fpm - ',
 '12/07/2025, 2:41\u202fpm - ',
 '12/07/2025, 2:41\u202fpm - ',
 '13/07/2025, 3:41\u202fam - ',
 '13/07/2025, 3:42\u202fam - ',
 '13/07/2025, 3:42\u202fam - ',
 '13/07/2025, 3:42\u202fam - ',
 '13/07/2025, 3:42\u202fam - ',
 '13/07/2025, 8:28\u202fam - ',
 '13/07/2025, 9:18\u202fam - ',
 '13/07/2025, 9:18\u202fam - ',
 '13/07/2025, 5:54\u202fpm - ',
 '15/07/2025, 12:09\u202fpm - ',
 '15/07/2025, 12:10\u202fpm - ',
 '15/07/2025, 12:10\u202fpm - ',
 '18/07/2025, 12:24\u202fpm - ',
 '02/08/2025, 2:59\u202fpm - ',
 '02/08/2025, 3:00\u202fpm - ',
 '02/08/2025, 3:00\u202fpm - ',
 '02/08/2025, 3:00\u202fpm - ',
 '08/08/2025, 5:44\u202fpm - ',
 '09/08/2025, 10:34\u202fam - ',
 '10/08/2025, 10:38\u202fam - ',
 '10/08/2025, 10:56\u202fam - ',
 '10/08/2025, 11:00\u202fam - ',
 '10/08/2025, 11:00\u202fam - ',
 '10/08/2025, 11:00\u202fam - ',
 '11/08/2025, 5:03\u202fpm - ',
 '11/08/2025, 5:03\u202fpm - ',
 '11/08/2025, 5:03\u202fpm - ',
 '11/08/2025, 5:08\u202fpm - ',
 '11/08/2025, 5:09\u202fpm - ',
 '11/08/2025, 6:01\u202fpm - ',
 '11/08/2025, 6:01\u202fpm - ',
 '11/08/2025, 6:01\u202fpm - ',
 '11/08/2025, 6:01\u202fpm - ',
 '11/08/2025, 6:01\u202fpm - ',
 '22/08/2025, 6:10\u202fpm - ',
 '24/08/2025, 10:53\u202fpm - ',
 '25/08/2025, 10:58\u202fam - ',
 '30/08/2025, 4:57\u202fpm - ',
 '30/08/2025, 5:15\u202fpm - ',
 '03/09/2025, 11:39\u202fpm - ',
 '03/09/2025, 11:39\u202fpm - ',
 '03/09/2025, 11:45\u202fpm - ',
 '03/09/2025, 11:45\u202fpm - ',
 '03/09/2025, 11:45\u202fpm - ',
 '03/09/2025, 11:45\u202fpm - ',
 '03/09/2025, 11:46\u202fpm - ',
 '03/09/2025, 11:47\u202fpm - ',
 '04/09/2025, 11:16\u202fpm - ',
 '09/09/2025, 6:22\u202fpm - ',
 '11/09/2025, 4:54\u202fpm - ',
 '11/09/2025, 4:54\u202fpm - ',
 '11/09/2025, 4:55\u202fpm - ',
 '11/09/2025, 4:55\u202fpm - ',
 '11/09/2025, 4:57\u202fpm - ',
 '11/09/2025, 4:57\u202fpm - ',
 '13/09/2025, 8:46\u202fpm - ',
 '24/09/2025, 11:21\u202fam - ',
 '24/09/2025, 11:22\u202fam - ',
 '24/09/2025, 11:23\u202fam - ',
 '24/09/2025, 11:23\u202fam - ',
 '24/09/2025, 11:23\u202fam - ',
 '24/09/2025, 11:23\u202fam - ',
 '24/09/2025, 11:23\u202fam - ',
 '24/09/2025, 11:23\u202fam - ',
 '24/09/2025, 11:23\u202fam - ',
 '24/09/2025, 11:24\u202fam - ',
 '24/09/2025, 11:24\u202fam - ',
 '24/09/2025, 11:24\u202fam - ',
 '24/09/2025, 11:24\u202fam - ',
 '24/09/2025, 8:18\u202fpm - ',
 '24/09/2025, 8:19\u202fpm - ',
 '24/09/2025, 8:19\u202fpm - ',
 '24/09/2025, 8:19\u202fpm - ',
 '24/09/2025, 8:19\u202fpm - ',
 '24/09/2025, 8:19\u202fpm - ',
 '24/09/2025, 8:19\u202fpm - ',
 '24/09/2025, 8:19\u202fpm - ',
 '24/09/2025, 8:19\u202fpm - ',
 '24/09/2025, 8:20\u202fpm - ',
 '24/09/2025, 8:22\u202fpm - ',
 '24/09/2025, 8:22\u202fpm - ',
 '24/09/2025, 8:22\u202fpm - ',
 '24/09/2025, 8:22\u202fpm - ',
 '24/09/2025, 8:22\u202fpm - ',
 '24/09/2025, 8:27\u202fpm - ',
 '24/09/2025, 8:27\u202fpm - ',
 '24/09/2025, 8:28\u202fpm - ',
 '24/09/2025, 8:28\u202fpm - ',
 '24/09/2025, 8:30\u202fpm - ',
 '24/09/2025, 8:30\u202fpm - ',
 '24/09/2025, 8:31\u202fpm - ',
 '24/09/2025, 8:32\u202fpm - ',
 '24/09/2025, 8:33\u202fpm - ',
 '24/09/2025, 8:33\u202fpm - ',
 '25/09/2025, 7:34\u202fpm - ',
 '25/09/2025, 7:35\u202fpm - ',
 '27/09/2025, 1:32\u202fam - ',
 '27/09/2025, 1:32\u202fam - ',
 '27/09/2025, 1:32\u202fam - ',
 '27/09/2025, 8:35\u202fpm - ',
 '27/09/2025, 8:36\u202fpm - ',
 '27/09/2025, 8:36\u202fpm - ',
 '27/09/2025, 8:36\u202fpm - ',
 '27/09/2025, 8:36\u202fpm - ',
 '27/09/2025, 8:36\u202fpm - ',
 '27/09/2025, 8:36\u202fpm - ',
 '27/09/2025, 8:36\u202fpm - ',
 '08/10/2025, 2:37\u202fpm - ',
 '08/10/2025, 3:22\u202fpm - ',
 '08/10/2025, 4:17\u202fpm - ',
 '10/10/2025, 5:15\u202fpm - ',
 '10/10/2025, 7:29\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:44\u202fpm - ',
 '23/10/2025, 8:46\u202fpm - ',
 '23/10/2025, 8:46\u202fpm - ',
 '23/10/2025, 8:46\u202fpm - ',
 '23/10/2025, 8:47\u202fpm - ',
 '23/10/2025, 8:47\u202fpm - ',
 '23/10/2025, 8:47\u202fpm - ',
 '23/10/2025, 8:47\u202fpm - ',
 '23/10/2025, 8:47\u202fpm - ',
 '28/10/2025, 12:58\u202fpm - ',
 '03/11/2025, 9:03\u202fam - ',
 '03/11/2025, 9:03\u202fam - ',
 '03/11/2025, 9:11\u202fam - ',
 '03/11/2025, 11:41\u202fam - ',
 '03/11/2025, 11:41\u202fam - ',
 '03/11/2025, 11:47\u202fam - ',
 '03/11/2025, 11:47\u202fam - ',
 '06/11/2025, 7:57\u202fam - ',
 '06/11/2025, 7:57\u202fam - ',
 '06/11/2025, 7:57\u202fam - ',
 '06/11/2025, 7:57\u202fam - ',
 '06/11/2025, 1:01\u202fpm - ',
 '22/11/2025, 5:50\u202fpm - ',
 '22/11/2025, 5:50\u202fpm - ',
 '22/11/2025, 5:50\u202fpm - ',
 '22/11/2025, 5:50\u202fpm - ',
 '22/11/2025, 5:58\u202fpm - ',
 '30/11/2025, 10:03\u202fam - ',
 '30/11/2025, 10:03\u202fam - ',
 '08/12/2025, 9:48\u202fam - ',
 '08/12/2025, 9:53\u202fam - ',
 '08/12/2025, 10:04\u202fam - ',
 '08/12/2025, 10:04\u202fam - ',
 '25/12/2025, 4:55\u202fpm - ',
 '25/12/2025, 4:56\u202fpm - ',
 '01/01/2026, 2:06\u202fpm - ',
 '01/01/2026, 2:06\u202fpm - ',
 '01/01/2026, 2:06\u202fpm - ',
 '01/01/2026, 2:06\u202fpm - ',
 '06/01/2026, 12:17\u202fpm - ',
 '17/01/2026, 5:41\u202fpm - ',
 '17/01/2026, 5:42\u202fpm - ',
 '17/01/2026, 5:42\u202fpm - ',
 '17/01/2026, 7:08\u202fpm - ',
 '17/01/2026, 7:08\u202fpm - ',
 '17/01/2026, 7:23\u202fpm - ',
 '18/01/2026, 1:27\u202fpm - ',
 '18/01/2026, 5:18\u202fpm - ',
 '18/01/2026, 5:18\u202fpm - ',
 '18/01/2026, 5:44\u202fpm - ',
 '18/01/2026, 9:00\u202fpm - ',
 '18/01/2026, 9:00\u202fpm - ',
 '18/01/2026, 9:58\u202fpm - ',
 '19/01/2026, 7:36\u202fpm - ',
 '19/01/2026, 7:46\u202fpm - ',
 '19/01/2026, 7:46\u202fpm - ',
 '19/01/2026, 8:08\u202fpm - ',
 '03/02/2026, 4:41\u202fpm - ',
 '03/02/2026, 4:44\u202fpm - ',
 '04/02/2026, 11:06\u202fam - ',
 '04/02/2026, 11:06\u202fam - ',
 '04/02/2026, 11:10\u202fam - ',
 '04/02/2026, 11:15\u202fam - ',
 '04/02/2026, 11:34\u202fam - ',
 '04/02/2026, 11:35\u202fam - ',
 '04/02/2026, 11:35\u202fam - ',
 '04/02/2026, 11:35\u202fam - ',
 '04/02/2026, 11:39\u202fam - ',
 '05/02/2026, 9:33\u202fam - ',
 '05/02/2026, 9:33\u202fam - ',
 '05/02/2026, 9:49\u202fam - ',
 '05/02/2026, 9:49\u202fam - ',
 '05/02/2026, 9:58\u202fam - ',
 '05/02/2026, 9:58\u202fam - ',
 '05/02/2026, 9:59\u202fam - ',
 '05/02/2026, 10:00\u202fam - ',
 '05/02/2026, 10:00\u202fam - ',
 '05/02/2026, 10:00\u202fam - ',
 '05/02/2026, 10:01\u202fam - ',
 '05/02/2026, 10:12\u202fam - ',
 '05/02/2026, 10:12\u202fam - ',
 '05/02/2026, 10:36\u202fam - ',
 '05/02/2026, 11:04\u202fam - ',
 '05/02/2026, 11:08\u202fam - ',
 '05/02/2026, 11:11\u202fam - ',
 '05/02/2026, 11:11\u202fam - ',
 '05/02/2026, 1:45\u202fpm - ',
 '05/02/2026, 1:48\u202fpm - ',
 '05/02/2026, 1:48\u202fpm - ',
 '05/02/2026, 1:49\u202fpm - ',
 '05/02/2026, 1:56\u202fpm - ',
 '05/02/2026, 1:56\u202fpm - ',
 '05/02/2026, 2:32\u202fpm - ',
 '05/02/2026, 2:32\u202fpm - ',
 '05/02/2026, 2:32\u202fpm - ',
 '05/02/2026, 2:32\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:33\u202fpm - ',
 '05/02/2026, 2:34\u202fpm - ',
 '05/02/2026, 3:12\u202fpm - ',
 '05/02/2026, 4:37\u202fpm - ',
 '05/02/2026, 5:09\u202fpm - ',
 '05/02/2026, 5:09\u202fpm - ',
 '05/02/2026, 5:09\u202fpm - ',
 '05/02/2026, 5:09\u202fpm - ',
 '05/02/2026, 5:10\u202fpm - ',
 '05/02/2026, 5:10\u202fpm - ',
 '05/02/2026, 5:10\u202fpm - ',
 '05/02/2026, 5:10\u202fpm - ',
 '05/02/2026, 5:10\u202fpm - ',
 '05/02/2026, 11:13\u202fpm - ',
 '06/02/2026, 12:01\u202fam - ',
 '06/02/2026, 8:51\u202fam - ',
 '06/02/2026, 8:59\u202fam - ',
 '06/02/2026, 8:59\u202fam - ',
 '06/02/2026, 9:11\u202fam - ',
 '08/02/2026, 11:10\u202fam - ',
 '09/02/2026, 3:37\u202fpm - ',
 '09/02/2026, 3:37\u202fpm - ',
 '09/02/2026, 8:20\u202fpm - ',
 '09/02/2026, 8:22\u202fpm - ',
 '09/02/2026, 8:25\u202fpm - ',
 '09/02/2026, 8:32\u202fpm - ',
 '09/02/2026, 8:32\u202fpm - ',
 '09/02/2026, 8:32\u202fpm - ',
 '09/02/2026, 8:32\u202fpm - ',
 '09/02/2026, 8:33\u202fpm - ',
 '09/02/2026, 8:33\u202fpm - ',
 '10/02/2026, 10:22\u202fam - ',
 '10/02/2026, 10:22\u202fam - ',
 '10/02/2026, 10:22\u202fam - ',
 '10/02/2026, 10:24\u202fam - ',
 '10/02/2026, 10:24\u202fam - ',
 '11/02/2026, 9:34\u202fpm - ',
 '11/02/2026, 9:58\u202fpm - ',
 '11/02/2026, 9:58\u202fpm - ',
 '11/02/2026, 9:59\u202fpm - ',
 '11/02/2026, 9:59\u202fpm - ',
 '11/02/2026, 9:59\u202fpm - ',
 '11/02/2026, 9:59\u202fpm - ',
 '11/02/2026, 9:59\u202fpm - ',
 '11/02/2026, 9:59\u202fpm - ',
 '11/02/2026, 10:06\u202fpm - ',
 '11/02/2026, 10:18\u202fpm - ',
 '11/02/2026, 10:18\u202fpm - ',
 '11/02/2026, 10:20\u202fpm - ',
 '11/02/2026, 10:20\u202fpm - ',
 '11/02/2026, 10:21\u202fpm - ',
 '11/02/2026, 10:21\u202fpm - ',
 '12/02/2026, 8:53\u202fam - ',
 '12/02/2026, 8:54\u202fam - ',
 '12/02/2026, 9:56\u202fam - ',
 '12/02/2026, 9:56\u202fam - ',
 '12/02/2026, 10:20\u202fam - ',
 '16/02/2026, 9:05\u202fpm - ',
 '17/02/2026, 7:33\u202fpm - ',
 '17/02/2026, 7:40\u202fpm - ',
 '17/02/2026, 7:41\u202fpm - ',
 '17/02/2026, 9:57\u202fpm - ',
 '17/02/2026, 9:58\u202fpm - ',
 '17/02/2026, 9:58\u202fpm - ',
 '17/02/2026, 9:58\u202fpm - ',
 '17/02/2026, 9:58\u202fpm - ',
 '17/02/2026, 9:58\u202fpm - ',
 '17/02/2026, 9:59\u202fpm - ',
 '17/02/2026, 9:59\u202fpm - ',
 '17/02/2026, 9:59\u202fpm - ',
 '17/02/2026, 9:59\u202fpm - ',
 '17/02/2026, 9:59\u202fpm - ',
 '17/02/2026, 9:59\u202fpm - ',
 '17/02/2026, 9:59\u202fpm - ',
 '17/02/2026, 9:59\u202fpm - ',
 '17/02/2026, 10:00\u202fpm - ',
 '17/02/2026, 11:15\u202fpm - ',
 '17/02/2026, 11:15\u202fpm - ',
 '17/02/2026, 11:15\u202fpm - ',
 '17/02/2026, 11:15\u202fpm - ',
 '17/02/2026, 11:15\u202fpm - ',
 '18/02/2026, 8:04\u202fam - ',
 '18/02/2026, 8:04\u202fam - ',
 '18/02/2026, 8:05\u202fam - ',
 '18/02/2026, 12:17\u202fpm - ',
 '20/02/2026, 2:26\u202fam - ',
 '20/02/2026, 8:04\u202fam - ',
 '20/02/2026, 11:27\u202fam - ',
 '28/02/2026, 12:41\u202fpm - ',
 '28/02/2026, 12:41\u202fpm - ',
 '28/02/2026, 12:42\u202fpm - ',
 '28/02/2026, 12:42\u202fpm - ',
 '28/02/2026, 12:44\u202fpm - ',
 '28/02/2026, 12:44\u202fpm - ',
 '28/02/2026, 12:44\u202fpm - ',
 '28/02/2026, 12:45\u202fpm - ',
 '02/03/2026, 12:04\u202fam - ',
 '02/03/2026, 12:04\u202fam - ',
 '09/03/2026, 5:03\u202fpm - ',
 '10/03/2026, 7:57\u202fpm - ',
 '11/03/2026, 8:55\u202fpm - ',
 '11/03/2026, 8:55\u202fpm - ',
 '11/03/2026, 8:55\u202fpm - ',
 '11/03/2026, 8:55\u202fpm - ',
 '11/03/2026, 9:00\u202fpm - ',
 '11/03/2026, 9:44\u202fpm - ',
 '11/03/2026, 9:44\u202fpm - ',
 '12/03/2026, 9:59\u202fam - ',
 '12/03/2026, 8:08\u202fpm - ',
 '12/03/2026, 9:39\u202fpm - ',
 '12/03/2026, 9:39\u202fpm - ',
 '12/03/2026, 11:03\u202fpm - ',
 '16/03/2026, 12:22\u202fam - ',
 '16/03/2026, 12:22\u202fam - ',
 '16/03/2026, 9:25\u202fam - ',
 '16/03/2026, 9:37\u202fam - ',
 '16/03/2026, 11:06\u202fam - ',
 '16/03/2026, 11:06\u202fam - ',
 '17/03/2026, 9:55\u202fam - ',
 '17/03/2026, 9:55\u202fam - ',
 '18/03/2026, 5:32\u202fpm - ',
 '19/03/2026, 8:14\u202fpm - ',
 '19/03/2026, 9:05\u202fpm - ',
 '19/03/2026, 11:59\u202fpm - ',
 '20/03/2026, 12:52\u202fpm - ',
 '20/03/2026, 12:53\u202fpm - ',
 '20/03/2026, 1:20\u202fpm - ',
 '20/03/2026, 7:35\u202fpm - ',
 '21/03/2026, 7:58\u202fpm - ',
 '02/04/2026, 8:29\u202fpm - ',
 '02/04/2026, 8:30\u202fpm - ',
 '02/04/2026, 9:38\u202fpm - ',
 '02/04/2026, 10:40\u202fpm - ',
 '04/04/2026, 11:24\u202fpm - ',
 '11/04/2026, 6:36\u202fpm - ',
 '13/04/2026, 11:34\u202fpm - ',
 '14/04/2026, 11:05\u202fam - ',
 '14/04/2026, 9:41\u202fpm - ',
 '15/04/2026, 2:42\u202fam - ',
 '15/04/2026, 8:54\u202fam - ',
 '15/04/2026, 9:31\u202fam - ',
 '15/04/2026, 9:39\u202fam - ',
 '15/04/2026, 11:22\u202fam - ',
 '15/04/2026, 6:15\u202fpm - ',
 '16/04/2026, 12:25\u202fam - ',
 '17/04/2026, 6:56\u202fpm - ',
 '17/04/2026, 8:25\u202fpm - ',
 '17/04/2026, 8:26\u202fpm - ',
 '17/04/2026, 8:27\u202fpm - ',
 '18/04/2026, 4:04\u202fam - ',
 '18/04/2026, 4:04\u202fam - ',
 '18/04/2026, 4:05\u202fam - ',
 '18/04/2026, 4:10\u202fam - ',
 '18/04/2026, 4:10\u202fam - ',
 '18/04/2026, 4:10\u202fam - ',
 '18/04/2026, 4:10\u202fam - ',
 '19/04/2026, 9:48\u202fpm - ',
 '19/04/2026, 9:59\u202fpm - ',
 '20/04/2026, 8:34\u202fpm - ',
 '21/04/2026, 9:49\u202fpm - ',
 '24/04/2026, 10:44\u202fam - ',
 '24/04/2026, 3:02\u202fpm - ',
 '24/04/2026, 3:05\u202fpm - ',
 '24/04/2026, 4:56\u202fpm - ',
 '24/04/2026, 4:56\u202fpm - ',
 '24/04/2026, 8:00\u202fpm - ',
 '24/04/2026, 8:01\u202fpm - ',
 '25/04/2026, 2:21\u202fpm - ',
 '25/04/2026, 2:21\u202fpm - ',
 '25/04/2026, 2:37\u202fpm - ',
 '25/04/2026, 2:53\u202fpm - ',
 '25/04/2026, 10:38\u202fpm - ',
 '25/04/2026, 10:38\u202fpm - ',
 '26/04/2026, 9:47\u202fam - ',
 '27/04/2026, 12:01\u202fam - ',
 '27/04/2026, 12:16\u202fam - ',
 '27/04/2026, 12:21\u202fam - ',
 '27/04/2026, 12:24\u202fam - ',
 '28/04/2026, 9:14\u202fam - ',
 '28/04/2026, 9:18\u202fam - ',
 '28/04/2026, 9:21\u202fam - ',
 '28/04/2026, 9:21\u202fam - ',
 '28/04/2026, 9:24\u202fam - ',
 '28/04/2026, 11:23\u202fam - ',
 '28/04/2026, 11:24\u202fam - ',
 '28/04/2026, 11:24\u202fam - ',
 '28/04/2026, 11:24\u202fam - ',
 '28/04/2026, 11:25\u202fam - ',
 '28/04/2026, 11:25\u202fam - ',
 '28/04/2026, 11:27\u202fam - ',
 '28/04/2026, 11:27\u202fam - ',
 '28/04/2026, 11:27\u202fam - ',
 '28/04/2026, 11:51\u202fam - ',
 '28/04/2026, 12:03\u202fpm - ',
 '28/04/2026, 8:43\u202fpm - ',
 '28/04/2026, 8:43\u202fpm - ',
 '28/04/2026, 8:53\u202fpm - ',
 '28/04/2026, 8:53\u202fpm - ',
 '02/05/2026, 4:40\u202fpm - ',
 '02/05/2026, 4:40\u202fpm - ',
 '02/05/2026, 4:40\u202fpm - ',
 '02/05/2026, 5:04\u202fpm - ',
 '02/05/2026, 5:04\u202fpm - ',
 '02/05/2026, 5:05\u202fpm - ',
 '02/05/2026, 5:22\u202fpm - ',
 '02/05/2026, 5:54\u202fpm - ',
 '02/05/2026, 5:55\u202fpm - ',
 '02/05/2026, 9:07\u202fpm - ',
 '02/05/2026, 9:08\u202fpm - ',
 '02/05/2026, 9:29\u202fpm - ',
 '02/05/2026, 9:33\u202fpm - ',
 '02/05/2026, 9:33\u202fpm - ',
 '02/05/2026, 9:39\u202fpm - ',
 '03/05/2026, 8:16\u202fam - ',
 '03/05/2026, 9:51\u202fam - ',
 '03/05/2026, 1:47\u202fpm - ',
 '03/05/2026, 1:53\u202fpm - ',
 '03/05/2026, 11:52\u202fpm - ',
 '04/05/2026, 5:06\u202fpm - ',
 '04/05/2026, 6:31\u202fpm - ',
 '04/05/2026, 6:51\u202fpm - ',
 '07/05/2026, 8:52\u202fpm - ',
 '07/05/2026, 8:52\u202fpm - ',
 '07/05/2026, 8:53\u202fpm - ',
 '07/05/2026, 8:53\u202fpm - ',
 '08/05/2026, 8:29\u202fam - ',
 '08/05/2026, 8:30\u202fam - ',
 '08/05/2026, 3:00\u202fpm - ',
 '08/05/2026, 3:00\u202fpm - ',
 '08/05/2026, 3:00\u202fpm - ',
 '08/05/2026, 3:27\u202fpm - ',
 '08/05/2026, 7:26\u202fpm - ',
 '08/05/2026, 7:32\u202fpm - ',

In [66]:
df = pd.DataFrame({
    'user_message': messages,
    'message_date': dates
    })

# Converting Message_Data type
df['message_date'] = df['message_date'].str.upper()
df['message_date'] = pd.to_datetime(
    df['message_date'], 
    format='%d/%m/%Y, %I:%M %p - '
    )

df.rename(
    columns={'message_date': 'date' },
    inplace=True
)

In [67]:
df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. O... 2025-05-10 00:52:00
1            Satya Prasad Avn Cse: <Media omitted>\n 2025-05-10 00:52:00
2            Satya Prasad Avn Cse: <Media omitted>\n 2025-05-10 00:55:00
3            Satya Prasad Avn Cse: <Media omitted>\n 2025-05-17 10:20:00
4                   Satya Prasad Avn Cse: Pick one\n 2025-05-17 10:20:00

In [68]:
df.shape

(695, 2)

In [73]:
# separating the user-name and user-data

users = []
messages = []

for message in df['user_message']:
    entry = re.split(r'([\w\W]+?):\s', message)
    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(" ".join(entry[2:]))
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace=True)

In [75]:
df.head(1)

,date,user,message
0,2025-05-10 00:52:00,group_notification,Messages and calls are end-to-end encrypted. O...

In [76]:
df['only_date'] = df['date'].dt.date
df['year'] = df['date'].dt.year
df['month_num'] = df['date'].dt.month
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day
df['day_name'] = df['date'].dt.day_name()
df['hour'] = df['date'].dt.hour
df['minute'] = df['date'].dt.minute

In [78]:
df.head(1)

,date,user,message,only_date,year,month_num,month,day,day_name,hour,minute
0,2025-05-10 00:52:00,group_notification,Messages and calls are end-to-end encrypted. O...,2025-05-10,2025,5,May,10,Saturday,0,52